# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.9
  displayName: 'Use Python 3.9'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install poetry
    cat requirements.txt | xargs poetry add
    poetry install
  displayName: Install poetry

- script: |
    poetry run python -m pytest
  displayName: Test software

- script: |
    poetry build
  displayName: Building package

- script: |
    echo $(PYPI-TOKEN)
    poetry config pypi-token.pypi $(PYPI-TOKEN)
    poetry publish -vvv
  displayName: Publishing to PyPI

- script: |
    python -m pip install visionai
    VISIONAI_EXEC=visionai python -m pytest
  displayName: Test visionai executable
