site_name: VisionAI
site_description: VisionAI Toolkit - Ready to use models & vision apps
site_url: https://docs.visionify.ai/

theme:
  name: material
  custom_dir: docs/overrides
  font:
    text: Open Sans
  palette:
    primary: black
    accent: teal
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  features:
    - navigation.tabs

repo_name: visionify/visionai
repo_url: https://github.com/visionify/visionai
edit_uri: ""

nav:
  - VisionAI:
    - Overview: index.md
    - Introduction: tutorial/index.md
    - First Steps: tutorial/first-steps.md
    - Printing and Colors: tutorial/printing.md
    - Terminating: tutorial/terminating.md
    - CLI Arguments:
        - CLI Arguments Intro: tutorial/arguments/index.md
        - Optional CLI Arguments: tutorial/arguments/optional.md
        - CLI Arguments with Default: tutorial/arguments/default.md
        - CLI Arguments with Help: tutorial/arguments/help.md
        - CLI Arguments with Environment Variables: tutorial/arguments/envvar.md
        - Other uses: tutorial/arguments/other-uses.md
    - CLI Options:
        - CLI Options Intro: tutorial/options/index.md
        - CLI Options with Help: tutorial/options/help.md
        - Required CLI Options: tutorial/options/required.md
        - CLI Option Prompt: tutorial/options/prompt.md
        - Password CLI Option and Confirmation Prompt: tutorial/options/password.md
        - CLI Option Name: tutorial/options/name.md
        - CLI Option Callback and Context: tutorial/options/callback-and-context.md
        - Version CLI Option, is_eager: tutorial/options/version.md
    - Commands:
        - Commands Intro: tutorial/commands/index.md
        - Command CLI Arguments: tutorial/commands/arguments.md
        - Command CLI Options: tutorial/commands/options.md
        - Command Help: tutorial/commands/help.md
        - Custom Command Name: tutorial/commands/name.md
        - Typer Callback: tutorial/commands/callback.md
        - One or Multiple Commands: tutorial/commands/one-or-multiple.md
        - Using the Context: tutorial/commands/context.md
    - CLI Option autocompletion: tutorial/options-autocompletion.md
    - CLI Parameter Types:
        - CLI Parameter Types Intro: tutorial/parameter-types/index.md
        - Number: tutorial/parameter-types/number.md
        - Boolean CLI Options: tutorial/parameter-types/bool.md
        - UUID: tutorial/parameter-types/uuid.md
        - DateTime: tutorial/parameter-types/datetime.md
        - Enum - Choices: tutorial/parameter-types/enum.md
        - Path: tutorial/parameter-types/path.md
        - File: tutorial/parameter-types/file.md
    - SubCommands - Command Groups:
        - SubCommands - Command Groups - Intro: tutorial/subcommands/index.md
        - Add Typer: tutorial/subcommands/add-typer.md
        - SubCommands in a Single File: tutorial/subcommands/single-file.md
        - Nested SubCommands: tutorial/subcommands/nested-subcommands.md
        - Sub-Typer Callback Override: tutorial/subcommands/callback-override.md
        - SubCommand Name and Help: tutorial/subcommands/name-and-help.md
    - Multiple Values:
        - Multiple Values Intro: tutorial/multiple-values/index.md
        - Multiple CLI Options: tutorial/multiple-values/multiple-options.md
        - CLI Options with Multiple Values: tutorial/multiple-values/options-with-multiple-values.md
        - CLI Arguments with Multiple Values: tutorial/multiple-values/arguments-with-multiple-values.md
    - Ask with Prompt: tutorial/prompt.md
    - Progress Bar: tutorial/progressbar.md
    - CLI Application Directory: tutorial/app-dir.md
    - Launching Applications: tutorial/launch.md
    - Testing: tutorial/testing.md
    - Using Click: tutorial/using-click.md
    - Building a Package: tutorial/package.md
    - Exceptions: tutorial/exceptions.md
  - Scenarios:
    - Overview: scenarios/index.md
    - Personnel Health:
      - PPE Detection: scenarios/ppe-detection.md
      - Working at heights: scenarios/working-at-heights.md
      - Slip and fall: scenarios/slip-and-fall.md
      - Confined spaces: scenarios/confined-spaces-dwell-duration-monitoring.md
      - Smoke and Fire: scenarios/smoke-and-fire-detection.md
      - Ergonomics: scenarios/posture-and-ergonomics.md
    - Company Policies:
      - Max Occupancy: scenarios/max-occupancy-count.md
      - Shipping activity: scenarios/shipping-activity.md
      - Unauthorized entry: scenarios/unauthorized-entry.md
      - No mobile usage: scenarios/no-phone-usage.md
      - No visitors: scenarios/no-visitors.md
      - No pictures: scenarios/no-taking-pictures.md
      - Occupancy: scenarios/person-occupancy.md
      - No food allowed: scenarios/no-food-allowed.md
      - No children: scenarios/no-children.md
    - Privacy:
      - Blur faces: preprocess/blur-faces.md
      - Blur signs/text: preprocess/blur-signs.md
      - Blur screens: preprocess/blur-screens.md
  - Typer CLI: typer-cli.md
  - Alternatives: alternatives.md
  - Help: help-typer.md
  - Developers: contributing.md
  - About: release-notes.md
  - Changelog: changelog/index.md

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tabbed:
      alternate_style: true

extra:
  analytics:
    provider: google
    property: G-3CWR3GL7BF
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/visionify/visionai
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/visionify
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hmurari
    - icon: fontawesome/brands/dev
      link: https://dev.to/hmurari
    - icon: fontawesome/brands/medium
      link: https://medium.com/@hmurari
    - icon: fontawesome/solid/globe
      link: https://visionify.ai
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/visionify-ai/

extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
  - js/termynal.js
  - js/custom.js